apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: contentservice
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: contentservice
  template:
    metadata:
      labels:
        app: contentservice
    spec: 
     containers:
      - name: contentservice
        image: it21048500/ds_content_service
        ports:
        - containerPort: 8004
        env:   
        - name: JWT_SECRET
          value: "MYSECRET"
        - name: JWT_EXPIRES_IN
          value: "24h"
        - name: PORT
          value: "8004"
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: contentservice
spec:
  type: NodePort
  ports:
  - port: 8004
    protocol: TCP
    targetPort: 8004
    nodePort: 32123
  selector:
    app: contentservice