apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: instructorservice
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: instructorservice
  template:
    metadata:
      labels:
        app: instructorservice
    spec: 
     containers:
      - name: instructorservice
        image: it21048500/ds_instructor_service
        ports:
        - containerPort: 8001
        env:   
        - name: JWT_SECRET
          value: "MYSECRET"
        - name: JWT_EXPIRES_IN
          value: "24h"
        - name: PORT
          value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: instructorservice
spec:
  type: NodePort
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
    nodePort: 32125
  selector:
    app: instructorservice