apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: authservice
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec: 
     containers:
      - name: authservice
        image: it21048500/ds_auth_service
        ports:
        - containerPort: 8000
        env:   
        - name: JWT_SECRET
          value: "MYSECRET"
        - name: JWT_EXPIRES_IN
          value: "24h"
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: authservice
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32124
  selector:
    app: authservice