apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: studentservice
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: studentservice
  template:
    metadata:
      labels:
        app: studentservice
    spec: 
     containers:
      - name: studentservice
        image: it21048500/ds_student_service
        ports:
        - containerPort: 8003
        env:   
        - name: JWT_SECRET
          value: "MYSECRET"
        - name: JWT_EXPIRES_IN
          value: "24h"
        - name: PORT
          value: "8003"
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: studentservice
spec:
  type: NodePort
  ports:
  - port: 8003
    protocol: TCP
    targetPort: 8003
    nodePort: 32122
  selector:
    app: studentservice